services:
  frontend:
    container_name: next-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    stdin_open: true

  backend:
    container_name: node-backend
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb

  sensor-simulator:
    container_name: sensor-simulator
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - backend
    command: node middlewares/cycleDataGenerator.js

  cleanup-cycle:
    container_name: cleanup-cycle
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - backend
    command: node middlewares/cleanupCycle.js


  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=spacey

volumes:
  mongo-data:
