services:
  frontend:
    container_name: react-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
      - DISABLE_WEBPACK_DEV_SERVER_DEPRECATION_WARNINGS=true
    stdin_open: true

  backend:
    container_name: node-backend
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=spacey

volumes:
  mongo-data: